### ISSUE TITLE
Consider using ~/.local/share for $default-dylan-directory

### ISSUE THREAD

**Issue by timClicks** [dylan-lang/pacman#2]
Noticed that the default location is `/opt/dylan`. The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has an opinion on this:

> `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used. 

Here is the relevant constant definition:

https://github.com/cgay/pacman/blob/74bc84d2f6338d745bd62faabffa40de327e9846/types.dylan#L23

**Comment by cgay** [comment]
I will update the code to follow https://specifications.freedesktop.org/basedir-spec/latest/ in general. Thanks for the nudge.
